version: '3.8'

services:
  alpha_arena:
    # build: .
    image: python:3.8-slim
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    working_dir: /app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    container_name: alpha_arena_bot
    command: /bin/bash
    tty: true
    stdin_open: true